language: node_js
node_js:
    - "node"
branches:
  only:
  - production
cache:
  directories:
    - "node_modules"
    - "$HOME/.npm"
before_install:
    - npm install exp -g
    - exp login --username $EXPO_USERNAME --password $EXPO_PASSWORD
install:
    - npm install
script:
    - npm run lint
    - npm run test